### ISSUE TITLE
Tests break since Zope 5.2.1

### ISSUE THREAD

**Issue by icemac** [zopefoundation/five.customerize#14]
Tests break on GHA since Zope 5.2.1: https://github.com/zopefoundation/five.customerize/runs/2813571197?check_suite_focus=true
The last time on Zope 5.2 they where still fine: https://github.com/zopefoundation/five.customerize/actions/runs/911694434

The traceback is:

```python
File ".../five.customerize/src/five/customerize/zpt.txt", line 27, in zpt.txt
Failed example:
    print(renderer())
Exception raised:
    Traceback (most recent call last):
      File "/opt/local/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/doctest.py", line 1336, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest zpt.txt[11]>", line 1, in <module>
        print(renderer())
      File ".../five.customerize/src/five/customerize/zpt.py", line 87, in __call__
        return template._exec(bound_names, args, kwargs)
      File ".../eggs/Zope-5.2.1-py3.9.egg/Products/PageTemplates/ZopePageTemplate.py", line 279, in _exec
        result = self.pt_render(extra_context=bound_names)
      File ".../eggs/Zope-5.2.1-py3.9.egg/Products/PageTemplates/ZopePageTemplate.py", line 343, in pt_render
        result = PageTemplate.pt_render(self, source, extra_context)
      File ".../eggs/Zope-5.2.1-py3.9.egg/Products/PageTemplates/PageTemplate.py", line 81, in pt_render
        return super().pt_render(
      File ".../eggs/zope.pagetemplate-4.5.0-py3.9.egg/zope/pagetemplate/pagetemplate.py", line 133, in pt_render
        return self._v_program(
      File ".../eggs/zope.pagetemplate-4.5.0-py3.9.egg/zope/pagetemplate/pagetemplate.py", line 265, in __call__
        interpreter()
      File ".../eggs/zope.tal-4.5-py3.9.egg/zope/tal/talinterpreter.py", line 274, in __call__
        self.interpret(self.program)
      File ".../eggs/zope.tal-4.5-py3.9.egg/zope/tal/talinterpreter.py", line 346, in interpret
        handlers[opcode](self, args)
      File ".../eggs/zope.tal-4.5-py3.9.egg/zope/tal/talinterpreter.py", line 534, in do_optTag_tal
        self.no_tag(stuff[-2], stuff[-1])
      File ".../eggs/zope.tal-4.5-py3.9.egg/zope/tal/talinterpreter.py", line 516, in no_tag
        self.interpret(program)
      File ".../eggs/zope.tal-4.5-py3.9.egg/zope/tal/talinterpreter.py", line 346, in interpret
        handlers[opcode](self, args)
      File ".../eggs/zope.tal-4.5-py3.9.egg/zope/tal/talinterpreter.py", line 627, in do_insertText_tal
        text = self.engine.evaluateText(stuff[0])
      File ".../eggs/Zope-5.2.1-py3.9.egg/Products/PageTemplates/Expressions.py", line 295, in evaluateText
        text = self.evaluate(expr)
      File ".../eggs/zope.tales-5.1-py3.9.egg/zope/tales/tales.py", line 775, in evaluate
        return expression(self)
       - /test_template
       - Line 2, Column 0
       - Expression: <PathExpr standard:'request/foo'>
       - Names:
          {'container': <Application at >,
           'context': <Application at >,
           'default': <object object at 0x11035fc40>,
           'here': <Application at >,
           'loop': {},
           'nothing': None,
           'options': {'args': ()},
           'repeat': <Products.PageTemplates.Expressions.SafeMapping object at 0x110f20100>,
           'request': <zope.publisher.browser.TestRequest instance URL=http://127.0.0.1>,
           'root': <Application at >,
           'template': <TTWViewTemplate at /test_template>,
           'user': <SpecialUser 'Anonymous User'>,
           'view': None}
      File ".../eggs/zope.tales-5.1-py3.9.egg/zope/tales/expressions.py", line 250, in __call__
        return self._eval(econtext)
      File ".../eggs/Zope-5.2.1-py3.9.egg/Products/PageTemplates/Expressions.py", line 213, in _eval
        ob = self._subexprs[-1](econtext)
      File ".../eggs/zope.tales-5.1-py3.9.egg/zope/tales/expressions.py", line 153, in _eval
        ob = self._traverser(ob, element, econtext)
      File ".../eggs/Zope-5.2.1-py3.9.egg/Products/PageTemplates/Expressions.py", line 109, in boboAwareZopeTraverse
        raise NotFound(name)
    zExceptions.NotFound: foo
```

Might there be a relation to the security fix made in Zope 5.2.1 even though the tales expression is `request/foo`?

cc: @dataflake @mauritsvanrees

**Comment by dataflake** [comment]
My guess: The `request` object is of type `zope.publisher.browser.TestRequest`. I am guessing that kind of Request object doesn't know about Zope/AccessControl-style security assertions? I didn't verify this.
